In [1]:
from pathlib import Path
from ec4py import *
from ec4py import Quantity_Value_Unit as QV
from ec4py.util_voltammetry import Voltammetry,find_vertex
from ec4py.ec_data_util import EC_Channels
import numpy as np
import matplotlib.pyplot as plt
import math
from ec4py.util_data import get_Impedance,calc_ir_manual

In [2]:
d = EC_Data()
d.E = np.linspace(-0.5, 0.5, 10)
d.i = np.linspace(-0.5, 0.5, 10)
d.Z_E = np.linspace(-0.5, 0.5, 10)
d.Phase_E = np.linspace(-0.5, 0.5, 10)

In [3]:
ch = EC_Channels()
print(ch.Voltage)

E


In [4]:
get_Impedance(d,ch)

get_Impedance 1 1 1


(array([-0.5       , -0.38888889, -0.27777778, -0.16666667, -0.05555556,
         0.05555556,  0.16666667,  0.27777778,  0.38888889,  0.5       ]),
 array([-0.5       , -0.38888889, -0.27777778, -0.16666667, -0.05555556,
         0.05555556,  0.16666667,  0.27777778,  0.38888889,  0.5       ]))

In [5]:
get_Impedance(d,ch)

get_Impedance 1 1 1


(array([-0.5       , -0.38888889, -0.27777778, -0.16666667, -0.05555556,
         0.05555556,  0.16666667,  0.27777778,  0.38888889,  0.5       ]),
 array([-0.5       , -0.38888889, -0.27777778, -0.16666667, -0.05555556,
         0.05555556,  0.16666667,  0.27777778,  0.38888889,  0.5       ]))

In [6]:
calc_ir_manual(d,ch,5)

(True,
 array([-2.5       , -1.94444444, -1.38888889, -0.83333333, -0.27777778,
         0.27777778,  0.83333333,  1.38888889,  1.94444444,  2.5       ]))

In [7]:

path_to_dataSetFolder = Path(".").cwd().parent.parent / "test_data" /"CV"
print(path_to_dataSetFolder)
#paths.append( path_to_dataSetFolder / "CV_144913_ 3.tdms")
#path = path_to_dataSetFolder / "CV_144700_ 3.tdms"

path = path_to_dataSetFolder / "CV_153333_ 3.tdms"

print(path.exists(),path)

path.exists()

c:\Users\gustav.wiberg\Documents\GitHub\NordicEC\EC4py\test_data\CV
True c:\Users\gustav.wiberg\Documents\GitHub\NordicEC\EC4py\test_data\CV\CV_153333_ 3.tdms


True

In [8]:
data = EC_Data(path)
print(data.Z_E)
data.i = np.ones(len(data.E))*2
print(len(data.E))
calc_ir_manual(data,ch,5)

[ 25.047913   23.283848   43.299076   33.93716    16.75543     7.1618857
  20.8689     21.561464   26.775846   41.278973   10.413817    8.478781
  13.42435    17.310009   18.049017   13.124125   11.087395    6.993512
   5.84771     9.286514   10.86308    14.538522    5.560598   12.207618
  23.371756    9.402861   11.967162    8.411881   11.241643    9.744847
  12.599336    9.392529    9.935853   11.890631   15.177905   10.870602
  10.5638685   9.06583     7.134733   12.821275   12.668372   16.438826
  13.997928   10.745408   15.329956    9.587695   14.121245    9.034022
  13.261856   13.826305   17.156233   21.071222   13.303533   12.372155
  18.671642   13.519036   16.10337     6.1080146  12.086991    8.330461
  14.049114   16.902666    9.048383   16.886532    7.495951    8.9742985
  18.795713   21.083876    9.586364    8.475901    6.150748   14.246004
  10.411965    8.665752    9.813134   11.762563   10.435085    8.733594
   7.823689   14.272783    9.150736   12.783981   13.133678   

(True, array([10., 10., 10., ..., 10., 10., 10.]))

In [9]:
imp, phase = get_Impedance(data,ch)

get_Impedance 0.019997999999999988 0.09998999999999994 0.019997999999999988
