In [1]:
import numpy as np

from ec4py.util_voltammetry import Voltammetry

In [2]:
data = Voltammetry(E_min=-2,E_max=2)

test_data = np.zeros(len(data.E))
test_data[data.get_index_of_E(0)]=1
larger_than = np.argwhere(test_data > 0.5)[0]
print(larger_than)

[2000]


In [3]:
data = Voltammetry(E_min=-2,E_max=2)
test_data = np.ones(len(data.E))
for i in range(data.get_index_of_E(0)):
    test_data[i]=0

print(test_data)
print(data.get_index_of_E(0),len(data.E))
current = test_data

i_threashold =0.5
options ={"tolerance": 0.1}

options["tolerance"] =0.1
smaller_than = np.argwhere(current < i_threashold-options["tolerance"])
larger_than = np.argwhere(current > i_threashold +options["tolerance"])
print(smaller_than)
start = np.max(smaller_than)
end  = np.min(larger_than)
print(start,end)       

[0. 0. 0. ... 1. 1. 1.]
2000 4001
[[   0]
 [   1]
 [   2]
 ...
 [1997]
 [1998]
 [1999]]
1999 2000


In [4]:
test_data = np.ones(len(data.E))
for i in range(data.get_index_of_E(0)):
    test_data[i]=0

i = data._get_E_at_i(test_data,0.5,tolerance=0.1)

In [5]:

data = Voltammetry(E_min=-2,E_max=2)
shift =data.get_index_of_E(0)
print(shift)
print(data.E)
data._shift_Current_Array(data.E, 1.0)


2000
[-2.    -1.999 -1.998 ...  1.998  1.999  2.   ]
shift_arrray 1000


array([-1.   , -0.999, -0.998, ...,    nan,    nan,    nan])